trigger:
- master
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(9651abbd-00b3-41aa-bf49-1f0ab63f8467)'
    appType: 'webApp'
    WebAppName: 'HangmanTest'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/hangman-tdd/'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


- script: npx ng test --watch=false
  displayName: 'Tests Hangman Karma'

